[libraries]
androidGradlePlugin = "com.android.tools.build:gradle:7.4.1"
androidXAppCompat = "androidx.appcompat:appcompat:1.1.0"
androidXConstraintLayout = "androidx.constraintlayout:constraintlayout:1.1.3"
androidXLifecycleCommon = "androidx.lifecycle:lifecycle-common:2.4.1"
androidXVectorDrawable = "androidx.vectordrawable:vectordrawable:1.1.0"
googleMaterial = "com.google.android.material:material:1.0.0"
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinStdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
nexusPublishPlugin = "io.github.gradle-nexus:publish-plugin:1.1.0"

androidXArchCoreTesting = "androidx.arch.core:core-testing:2.1.0"
androidXFragmentTesting = "androidx.fragment:fragment-testing:1.5.5"
androidXTestCoreKtx = "androidx.test:core-ktx:1.4.0"
androidXTestExtJunit = "androidx.test.ext:junit:1.1.3"
junit = "junit:junit:4.13.2"
robolectric = "org.robolectric:robolectric:4.9.2"
truth = "com.google.truth:truth:1.1.3"

[versions]
kotlin = "1.7.20"
